server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
xuecheng:
  mq:
   queue: queue_cms_postpage_03  #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
   routingKey: 5e1ed2e2e1940f6b5f1461da #此routingKey为门户站点ID